# Generated by Django 3.0.8 on 2020-09-20 22:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(default='NMN', max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Nonbinary')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('current_school', models.CharField(max_length=200)),
                ('current_grade', models.CharField(max_length=200)),
                ('has_sibling', models.BooleanField(null=True)),
                ('sibling_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sibling_grade', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=200)),
                ('form_display_value', models.CharField(max_length=200)),
                ('display_on_form', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_parent_name', models.CharField(max_length=200, null=True)),
                ('secondary_parent_relation', models.CharField(max_length=200, null=True)),
                ('secondary_parent_email', models.EmailField(max_length=254, null=True)),
                ('secondary_parent_phone_number', models.CharField(max_length=12, null=True)),
                ('applicant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applications.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('applicant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applications.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('school_year', models.CharField(max_length=200)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.CharField(max_length=200)),
                ('how_did_you_hear', models.CharField(max_length=200, null=True)),
                ('other_hear_option', models.CharField(max_length=200, null=True)),
                ('agree_to_terms', models.BooleanField(null=True)),
                ('applicant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applications.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('applicant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applications.Applicant')),
            ],
        ),
    ]
