# Generated by Django 3.0.8 on 2020-09-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20200920_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='has_sibling',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='other_hear_option',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
