# Generated by Django 3.0.8 on 2020-11-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20200920_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='lottery_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
