# Generated by Django 3.0.8 on 2020-11-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicant_lottery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='lottery_status',
            field=models.CharField(blank=True, choices=[('Lottery', 'Lottery'), ('Waitlist', 'Waitlist'), ('Admitted', 'Admitted'), ('Registered', 'Registered')], default='Lottery', max_length=200, null=True),
        ),
    ]
