# Generated by Django 3.0.8 on 2020-11-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20201121_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='waitlist_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
