# Generated by Django 3.0.8 on 2020-11-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_applicant_waitlist_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='waitlist_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
